#!/bin/ash
#
# There is a reference to /dev/hda11 which happens to be eric's root.
# Brett uses /dev/hda10 because he only has one swap partition.
#
# Yes, this value should be injected/auto-adjusted rather than hard-coded.
#
# Better yet, we could build busybox with fdisk (which we want anyway)
# and grep or sed and search for the bootable partition marked with an
# asterisk
#

PATH=/sbin:/bin
export PATH

echo "STARTING INIT"

mount -t sysfs none /sys
mount -t proc none /proc
mount -t tmpfs mdev /dev

echo "Creating device nodes..."
echo mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

#
# This activates the hard disk.  The timing is quite sensitive.
# Shorter sleeps will certainly work but removing the sleeps
# entirely prevents the hard disk from being recognized.  We do
# not yet understand why.
#
echo "activating hard disk"
cd /modules
echo "insmod diag.ko"
insmod diag.ko
sleep 10

echo "enabling pci devices"
echo "there will be some errors below -- ignore them."
cd /sys/devices/pci0000:00
for FILE in */enable
do 
    echo -n 1 > $FILE
done
echo "there will be some errors above -- ignore them."

cd /modules
sleep 5
echo "insmod ide-core.ko"
insmod ide-core.ko

sleep 5
echo "insmod ide-gd_mod.ko"
insmod ide-gd_mod.ko

sleep 5
echo "insmod aec62xx.ko"
insmod aec62xx.ko

echo "Re-running mdev to create new hard disk nodes"
mdev -s

echo "mount /dev/hda11 /mnt"
mount /dev/hda11 /mnt

cd /mnt

echo "umounting virtual filesystems from old root"
umount /sys
umount /proc
umount /dev/pts
umount /dev

echo "exec switch_root -c /dev/console /mnt /sbin/init"
exec switch_root -c /dev/console /mnt /sbin/init

echo "switch_root didn't exec and somehow we got here. bail out."
exec /bin/ash
