#!/bin/sh
#
# ROOT needs to be the correct root device name (for the real
# root filesystem).  For brett this is /dev/hde10. For eric it is
# /dev/hde11.
#
# Yes, this value should be injected/auto-adjusted rather than hard-coded
#
# Better yet, we could build busybox with fdisk (which we want anyway)
# and grep or sed and search for the bootable partition marked with an
# asterisk
#

ROOT=/dev/hde10

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

mount -t sysfs none /sys
mount -t proc none /proc

mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo "Creating device nodes..."
echo mdev > /proc/sys/kernel/hotplug
mdev -s

# This activates the hard disk.
# The timing is quite sensitive.  Shorter sleeps will certainly
# work but removing the sleeps entirely prevents the hard disk
# from being recognized.  We do not yet understand why.
echo "activating hard disk"
cd /modules
echo "insmod diag.ko"
insmod diag.ko
sleep 10

echo "enabling pci devices"
cd /sys/devices/pci0000:00
for FILE in */enable
do 
    echo -n 1 > $FILE
done

cd /modules
sleep 5
echo "insmod ide-core.ko"
insmod ide-core.ko

sleep 5
echo "insmod ide-gd_mod.ko"
insmod ide-gd_mod.ko

sleep 5
echo "insmod aec62xx.ko"
insmod aec62xx.ko

echo "mount $ROOT /mnt"
mount $ROOT /mnt

echo "chrooting"
exec switch_root -c /dev/console /mnt /sbin/init
