#!/bin/bash
#

#SSBL is where we want to build the Second Stage Boot Loader root
export SSBL=/tmp/ssbl
export KERNEL=/usr/local/rnd/toolchain/linux
export FREESA=$(pwd)

if [ ! -f ${SSBL}/bin/busybox ]
then
    echo "First build and install busybox to create the skeleton of SSBL!"
    echo "copy the config file to .config, then make oldconfig && "
    echo "make && make install"
    exit 0
fi

install -dv -m 1777 ${SSBL}/tmp
mkdir -v ${SSBL}/dev
mkdir -v ${SSBL}/etc
mkdir -v ${SSBL}/mnt
mkdir -v ${SSBL}/modules
mkdir -v ${SSBL}/proc
mkdir -v ${SSBL}/sys
