#!/bin/bash
#

#SSBL is where we want to build the Second Stage Boot Loader root
export SSBL=/opt/ssbl
export FREESA=/home/eric/src/freesa
export BUSYBOX=/opt/bbox/busybox-1.13.1

mkdir -pv ${SSBL}
mkdir -v ${SSBL}/etc
#mkdir -v ${SSBL}/etc/fstab
mkdir -v ${SSBL}/etc/opt
mkdir -v ${SSBL}/mnt
mkdir -v ${SSBL}/modules
cp /usr/src/kernel/linux/drivers/ide/pci/aec62xx.ko ${SSBL}/modules/
cp /usr/src/diag/diag/diag.ko ${SSBL}/modules/
cp /usr/src/kernel/linux/drivers/ide/ide-core.ko ${SSBL}/modules/
cp /usr/src/kernel/linux/drivers/ide/ide-disk.ko ${SSBL}/modules/
mkdir -v ${SSBL}/new-root
mkdir -v ${SSBL}/proc
mkdir -v ${SSBL}/sbin
cp ${FREESA}/ssbl/init-ssbl ${SSBL}/sbin/
cp ${BUSYBOX}/busybox ${SSBL}/sbin/
cd ${SSBL}/sbin
ln -s init-ssbl init
ln -s busybox chroot
ln -s busybox depmod
ln -s busybox echo
ln -s busybox hush
ln -s busybox insmod
ln -s busybox lsmod
ln -s busybox mdev
ln -s busybox modprobe
ln -s busybox mount
ln -s busybox pivot_root
ln -s busybox rmmod
ln -s busybox sh
ln -s busybox sleep
mkdir -v ${SSBL}/sys
install -dv -m 1777 ${SSBL}/tmp
echo ""
mkdir -v ${SSBL}/dev
mknod -m 600 ${SSBL}/dev/console c 5 1
mknod -m 666 ${SSBL}/dev/null c 1 3
echo ""
echo "CHECK NOW:"
echo ""
echo "1.  the /sbin/chroot specified in the init script must reside in"
echo "    the same /sbin/chroot location. You may need to move or symlink it"
echo "    from the /usr/sbin/chroot on the hard disk as noted in"
echo "      man 8 pivot_root"
echo ""
echo "2.  the init script puts the original root in /old_root"
echo "    make sure that /old_root exists on the hard disk"
echo ""
echo "3.  you may need to be root to execute mknode either delay this step"
echo "    or perhaps try:"
echo "      sudo mknod -m 600 ${SSBL}/dev/console c 5 1"
echo "      sudo mknod -m 666 ${SSBL}/dev/null c 1 3"
echo ""
echo "3.  Cheers and good luck"
echo ""

