#!/bin/bash

export PATH=/tmp/cross-tools/bin:/opt/gcc440/bin:$PATH
export LC_ALL=POSIX
unset CFLAGS
unset CXXFLAGS

mkdir -p /tmp/Build/logs

if [ -f "build-toolchain-$1.rb" ]
then
    time ruby -I $HOME/gits/litbuild/lib build-toolchain-$1.rb $2
else
    echo "run as: $0 {eglibc,glibc,uclibc} {mips,x86}"
fi
