#!/bin/bash
#
# TODO: this might be more fun if it were in ruby.
#
# This version just installs a standard toolchain into $SYSROOT,
# wherever that is.  Since we have a /cross-toolchain directory
# for our cross-tools, let's put it under there.

export CLFS=/home/clfs
export CLFS_HOST=i686-cross-linux-gnu
export CLFS_TARGET=mipsel-unknown-linux-gnu
export GLIBCFLAG="-g -O2"
export KERNEL_ARCH="ARCH=mips"
export KERNEL_VERSION=2.6.23
export LC_ALL=POSIX
export PATH=/cross-tools/bin:/bin:/usr/bin
export SYSROOT=/cross-tools/sysroot
unset CFLAGS
unset CXXFLAGS

set -e

function step00_prepare_sources()
{
git clone $CLFS/Toolchain/binutils
{ pushd binutils && git checkout with-clfs-patches && popd ; } 2>&1 
git clone $CLFS/Toolchain/gcc
{ pushd gcc && git checkout with-posix-patch && popd ; } 2>&1
git clone $CLFS/Toolchain/glibc
{ pushd glibc && git checkout with-clfs-and-gcc430-patches && popd ; } 2>&1
git clone $CLFS/Toolchain/linux
{ pushd linux && git checkout openwrt-plus-freesa && popd ; } 2>&1
}

function step01_kernel_headers()
{
make mrproper &&
make $KERNEL_ARCH headers_check &&
make $KERNEL_ARCH headers_install INSTALL_HDR_PATH=$SYSROOT/usr &&
echo WOOT
}

function step02_binutils()
{
../binutils/configure --prefix=/cross-tools \
   --build=${CLFS_HOST} --target=${CLFS_TARGET} \
   --disable-nls --enable-shared --disable-multilib \
   --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
make configure-host && make && make install &&
cp -v ../binutils*/include/libiberty.h $SYSROOT/usr/include &&
echo WOOT
}

function step03_glibc_headers()
{
CC=gcc ../glibc/configure --prefix=/usr \
  --host=${CLFS_HOST} --build=${CLFS_TARGET} \
  --disable-sanity-checks --enable-kernel=${KERNEL_VERSION} \
  --with-headers=$SYSROOT/usr/include \
  --with-binutils=/cross-tools/${CLFS_TARGET}/bin &&
make cross-compiling=yes install_root=$SYSROOT install-headers &&
cp -v bits/stdio_lim.h $SYSROOT/usr/include/bits &&
touch $SYSROOT/usr/include/gnu/stubs.h &&
cp -v ../glibc*/nptl/sysdeps/pthread/pthread.h $SYSROOT/usr/include &&
cp -v ../glibc*/nptl/sysdeps/unix/sysv/linux/i386/bits/pthreadtypes.h \
  $SYSROOT/usr/include/bits &&
echo WOOT
}

function step04_gcc_bare()
{
../gcc/configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
  --disable-multilib \
  --disable-nls --disable-shared \
  --disable-libmudflap --disable-libssp \
  --disable-threads --enable-languages=c \
  --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
export LDFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
export CPPFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
make all-gcc && make install-gcc &&
echo WOOT
}

function step05_glibc_startup()
{
echo "libc_cv_forced_unwind=yes" > config.cache
echo "libc_cv_c_cleanup=yes" >> config.cache
BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc" \
    AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
    CFLAGS="${GLIBCFLAG}" \
    ../glibc/configure --prefix=/usr \
    --host=${CLFS_TARGET} --build=${CLFS_HOST} \
    --disable-profile --enable-add-ons \
    --with-tls --enable-kernel=${KERNEL_VERSION} --with-__thread \
    --with-binutils=/cross-tools/bin --with-headers=$SYSROOT/usr/include \
    --cache-file=config.cache &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crt1.o &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crti.o &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crtn.o &&
mkdir -p $SYSROOT/lib &&
cp csu/crt{1,i,n}.o $SYSROOT/lib &&
echo WOOT
}

function step06_gcc_libgcc()
{
make all-target-libgcc && make install-target-libgcc && 
rm -f $SYSROOT/lib/crt{1,i,n}.o &&
echo WOOT
}

function step07_glibc_full()
{
echo "libc_cv_forced_unwind=yes" > config.cache
echo "libc_cv_c_cleanup=yes" >> config.cache
BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc" \
    AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
    CFLAGS="$GLIBCFLAG" \
    ../glibc/configure --prefix=/usr \
    --host=${CLFS_TARGET} --build=${CLFS_HOST} \
    --disable-profile --enable-add-ons \
    --with-tls --enable-kernel=${KERNEL_VERSION} --with-__thread \
    --with-binutils=/cross-tools/bin --with-headers=$SYSROOT/usr/include \
    --cache-file=config.cache &&
make && 
make install_root=$SYSROOT install && 
echo WOOT
}

function step08_gcc_full()
{
../gcc/configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
  --disable-multilib \
  --disable-nls --enable-shared \
  --enable-languages=c,c++ --enable-__cxa_atexit \
  --enable-c99 --enable-long-long --enable-threads=posix \
  --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
export LDFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
export CPPFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
make AS_FOR_TARGET="${CLFS_TARGET}-as" LD_FOR_TARGET="${CLFS_TARGET}-ld" &&
make install &&
echo WOOT
}

function step09_kernel_headers_for_tools()
{
make mrproper &&
make $KERNEL_ARCH headers_check &&
make $KERNEL_ARCH headers_install INSTALL_HDR_PATH=/tools/usr &&
echo WOOT
}

function step10_glibc_tools()
{
echo "libc_cv_forced_unwind=yes" > config.cache
echo "libc_cv_c_cleanup=yes" >> config.cache
BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc" \
    AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
    CFLAGS="$GLIBCFLAG" \
    ../glibc/configure --prefix=/tools \
    --host=${CLFS_TARGET} --build=${CLFS_HOST} \
    --disable-profile --enable-add-ons \
    --with-tls --enable-kernel=${KERNEL_VERSION} --with-__thread \
    --with-binutils=/cross-tools/bin --with-headers=/tools/usr/include \
    --cache-file=config.cache &&
make && 
make install_root=$CLFS install && 
echo WOOT
}

function step11_specs()
{
${CLFS_TARGET}-gcc -dumpspecs | sed -e 's@/lib/ld@/tools/lib/ld@g' > \
   $(dirname $(${CLFS_TARGET}-gcc --print-libgcc-file-name))/specs
}

unset CC CXX AR AS RANLIB LD STRIP

BUILD_DIR=$PWD

echo "clearing out old stuff, I hope that's what you wanted."

rm -rf $CLFS/{etc,lib,sbin,usr,tools,cross-tools}
mkdir -p $CLFS/tools
mkdir -p $CLFS/cross-tools
rm -rf build-binutils build-glibc build-gcc

if [ -d ${BUILD_DIR}/Logs ]
then
    mv ${BUILD_DIR}/Logs ${BUILD_DIR}/Logs-$(date "+%Y-%m-%d-%H%M%S")
fi
mkdir ${BUILD_DIR}/Logs

echo "Starting at $(date)" > ${BUILD_DIR}/Logs/timing.txt

if [ ! -d binutils ]
then
    echo "STEP 00"
    step00_prepare_sources > ${BUILD_DIR}/Logs/step00.txt
fi

echo "STEP 01"
cd linux
step01_kernel_headers > ${BUILD_DIR}/Logs/step01.txt
cd ${BUILD_DIR}

echo "STEP 02"
mkdir build-binutils && cd build-binutils
step02_binutils > ${BUILD_DIR}/Logs/step02.txt
cd ${BUILD_DIR}
rm -rf build-binutils

echo "STEP 03"
mkdir build-glibc && cd build-glibc
step03_glibc_headers > ${BUILD_DIR}/Logs/step03.txt
cd ${BUILD_DIR}
rm -rf build-glibc

echo "STEP 04"
mkdir build-gcc && cd build-gcc
step04_gcc_bare > ${BUILD_DIR}/Logs/step04.txt
cd ${BUILD_DIR}

echo "STEP 05"
mkdir build-glibc && cd build-glibc
step05_glibc_startup > ${BUILD_DIR}/Logs/step05.txt
cd ${BUILD_DIR}
rm -rf build-glibc

echo "STEP 06"
cd build-gcc
step06_gcc_libgcc > ${BUILD_DIR}/Logs/step06.txt
cd ${BUILD_DIR}
rm -rf build-gcc

echo "STEP 07"
mkdir build-glibc && cd build-glibc
step07_glibc_full > ${BUILD_DIR}/Logs/step07.txt
cd ${BUILD_DIR}
rm -rf build-glibc

echo "STEP 08"
mkdir build-gcc && cd build-gcc
step08_gcc_full > ${BUILD_DIR}/Logs/step08.txt
cd ${BUILD_DIR}
rm -rf build-gcc

echo "STEP 09"
cd linux
step09_kernel_headers_for_tools > ${BUILD_DIR}/Logs/step09.txt
cd ${BUILD_DIR}

echo "STEP 10"
mkdir build-glibc && cd build-glibc
step10_glibc_tools > ${BUILD_DIR}/Logs/step10.txt
cd ${BUILD_DIR}
rm -rf build-glibc

echo "STEP 11"
step11_specs > ${BUILD_DIR}/Logs/step11.txt

echo "Ended at $(date)" >> ${BUILD_DIR}/Logs/timing.txt

echo "WOOT WOOT WOOT WOOT"
