#!/bin/bash
#
# TODO: this would be more fun if it were in ruby.

set -e

function step1_kernel_headers()
{
  make mrproper &&
  make $KERNEL_ARCH headers_check &&
  make $KERNEL_ARCH headers_install INSTALL_HDR_PATH=$SYSROOT/usr &&
  echo WOOT
}

function step2_binutils()
{
../binutils/configure --prefix=/cross-tools \
   --build=${CLFS_HOST} --target=${CLFS_TARGET} \
   --disable-nls --enable-shared --disable-multilib \
   --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
make configure-host && make && make install &&
cp -v ../binutils*/include/libiberty.h $SYSROOT/usr/include &&
echo WOOT
}

function step3_glibc_headers()
{
CC=gcc ../glibc/configure --prefix=/usr \
  --host=${CLFS_HOST} --build=${CLFS_TARGET} \
  --disable-sanity-checks --enable-kernel=${KERNEL_VERSION} \
  --with-headers=$SYSROOT/usr/include \
  --with-binutils=/cross-tools/${CLFS_TARGET}/bin &&
make cross-compiling=yes install_root=$SYSROOT install-headers &&
cp -v bits/stdio_lim.h $SYSROOT/usr/include/bits &&
touch $SYSROOT/usr/include/gnu/stubs.h &&
cp -v ../glibc*/nptl/sysdeps/pthread/pthread.h $SYSROOT/usr/include &&
cp -v ../glibc*/nptl/sysdeps/unix/sysv/linux/i386/bits/pthreadtypes.h \
  $SYSROOT/usr/include/bits &&
echo WOOT
}

function step4_gcc_bare()
{
../gcc/configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
  --disable-multilib \
  --disable-nls --disable-shared \
  --disable-libmudflap --disable-libssp \
  --disable-threads --enable-languages=c \
  --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
export LDFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
export CPPFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
make all-gcc && make install-gcc &&
echo WOOT
}

function step5_glibc_startup()
{
echo "libc_cv_forced_unwind=yes" > config.cache
echo "libc_cv_c_cleanup=yes" >> config.cache
BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc" \
    AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
    CFLAGS="${GLIBCFLAG}" \
    ../glibc/configure --prefix=/usr \
    --host=${CLFS_TARGET} --build=${CLFS_HOST} \
    --disable-profile --enable-add-ons \
    --with-tls --enable-kernel=${KERNEL_VERSION} --with-__thread \
    --with-binutils=/cross-tools/bin --with-headers=$SYSROOT/usr/include \
    --cache-file=config.cache &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crt1.o &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crti.o &&
make -r -C ../glibc/csu objdir=$(pwd) $(pwd)/csu/crtn.o &&
mkdir -p $SYSROOT/lib &&
cp csu/crt{1,i,n}.o $SYSROOT/lib &&
echo WOOT
}

function step6_gcc_libgcc()
{
make all-target-libgcc && make install-target-libgcc && 
rm -f $SYSROOT/lib/crt{1,i,n}.o &&
echo WOOT
}

function step7_glibc_full()
{
echo "libc_cv_forced_unwind=yes" > config.cache
echo "libc_cv_c_cleanup=yes" >> config.cache
BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc" \
    AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
    CFLAGS="$GLIBCFLAG" \
    ../glibc/configure --prefix=/tools \
    --host=${CLFS_TARGET} --build=${CLFS_HOST} \
    --disable-profile --enable-add-ons \
    --with-tls --enable-kernel=${KERNEL_VERSION} --with-__thread \
    --with-binutils=/cross-tools/bin --with-headers=$SYSROOT/usr/include \
    --cache-file=config.cache &&
make && 
make install_root=/ install && 
echo WOOT
}

function step8_gcc_full()
{
../gcc/configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
  --disable-multilib \
  --disable-nls --enable-shared \
  --enable-languages=c,c++ --enable-__cxa_atexit \
  --enable-c99 --enable-long-long --enable-threads=posix \
  --with-sysroot=$SYSROOT --with-build-sysroot=$SYSROOT &&
export LDFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
export CPPFLAGS_FOR_TARGET="--sysroot=$SYSROOT" &&
make AS_FOR_TARGET="${CLFS_TARGET}-as" LD_FOR_TARGET="${CLFS_TARGET}-ld" &&
make install &&
echo WOOT
}

function step9_specs()
{
${CLFS_TARGET}-gcc -dumpspecs | sed -e 's@/lib/ld@/tools/lib/ld@g' > \
   $(dirname $(${CLFS_TARGET}-gcc --print-libgcc-file-name))/specs
}


BUILD_DIR=$PWD
for dir in binutils gcc glibc linux
do
    if [ ! -d $dir ]
    then
        echo "toolchain directories aren't here"
        exit 1
    fi
done

if [ -z $SYSROOT ]
then
    echo "environment variables aren't all set"
    exit 2
fi

if [ -z ${CLFS_TARGET} ]
then
    echo "environment variables aren't all set"
    exit 2
fi

if [ -z ${CLFS_HOST} ]
then
    echo "environment variables aren't all set"
    exit 2
fi

echo "clearing out tools, I hope that's what you wanted."
rm -rf /tools/*
rm -rf /cross-tools/*
rm -rf binutils-build glibc-build gcc-build
mkdir -p ${BUILD_DIR}/Logs

echo "STEP 1"
pushd linux
step1_kernel_headers > ${BUILD_DIR}/Logs/step1.txt
popd

echo "STEP 2"
mkdir binutils-build && pushd binutils-build
step2_binutils > ${BUILD_DIR}/Logs/step2.txt
popd && rm -rf binutils-build

echo "STEP 3"
mkdir glibc-build && pushd glibc-build
step3_glibc_headers > ${BUILD_DIR}/Logs/step3.txt
popd && rm -rf glibc-build

echo "STEP 4"
mkdir gcc-build && pushd gcc-build
step4_gcc_bare > ${BUILD_DIR}/Logs/step4.txt
popd

echo "STEP 5"
mkdir glibc-build && pushd glibc-build
step5_glibc_startup > ${BUILD_DIR}/Logs/step5.txt
popd && rm -rf glibc-build

echo "STEP 6"
pushd gcc-build
step6_gcc_libgcc > ${BUILD_DIR}/Logs/step6.txt
popd && rm -rf gcc-build

echo "STEP 7"
mkdir glibc-build && pushd glibc-build
step7_glibc_full > ${BUILD_DIR}/Logs/step7.txt
popd && rm -rf glibc-build

rm -f $CLFS/tools/tools
ln -s . $CLFS/tools/tools

echo "STEP 8"
mkdir gcc-build && cd gcc-build
step8_gcc_full > ${BUILD_DIR}/Logs/step8.txt
popd && rm -rf gcc-build

echo "STEP 9"
step9_specs > ${BUILD_DIR}/Logs/step9.txt

echo "WOOT WOOT WOOT WOOT"


